services:
  # Backend API service
  - type: web
    name: homework-mentor-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: OPENAI_API_KEY
        sync: false
    autoDeploy: true

  # Frontend static site
  - type: web
    name: homework-mentor-frontend
    env: node
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm run preview
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
    autoDeploy: true
